services:
  postgres:
    image: "postgres:14.5"
    ports:
      - "${VITE_DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${VITE_DB_NAME}"
      POSTGRES_USER: "${VITE_DB_USERNAME}"
      POSTGRES_PASSWORD: "${VITE_DB_PASSWORD}"
